# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026 Alexandra Bernadotte
"""The vault meets its first German file (23.09.2026).

Four defects, each measured on a demo document set, each pinned here at its source:
  * the English NER read German common nouns as people ("Die Wohnung", "Eine Kündigung",
    "Ihr Recht") — a language without a model now gets only the regex recognisers;
  * the splitter enrolled the form of address "Herrn" as a man's given name;
  * the glossary called a GmbH "organisation" — and the legal form can decide an answer;
  * the glossary certified German names as written "in Cyrillic and Latin script" on the
    strength of transliterations the vault itself generated.
Plus the reconcile rule for a shared name part whose names are all gone.
"""

from __future__ import annotations

from types import SimpleNamespace

import pytest

from deidkit import namefold as nf
from deidkit.detect import PRESIDIO_KIND, STRUCTURAL_KINDS, PresidioDetector
from deidkit.glossary import build_glossary, legal_form_of
from harness import Scope, token_row


@pytest.mark.parametrize("span", ["Die Wohnung", "Eine Kündigung", "Ihr Recht", "Sehr geehrte",
                                  "Insert Title", "Insert Rate", "Insert Address", "Der Vermieter"])
def test_german_phrases_and_template_placeholders_are_not_people(span):
    ok, why = nf.admit_person(span)
    assert not ok, (span, why)


@pytest.mark.parametrize("span", ["Paul Winter", "Ada Brenner", "Herrn Paul Winter",
                                  "Frau Dr. Ada Brenner"])
def test_real_german_names_are_still_admitted(span):
    ok, why = nf.admit_person(span)
    assert ok, (span, why)


def test_a_form_of_address_is_never_a_name_part():
    parts = [p for p, _role in nf.person_fragments("Herrn Paul Winter")]
    assert "Herrn" not in parts and "Paul" in parts and "Winter" in parts
    parts = [p for p, _role in nf.person_fragments("Frau Dr. Ada Brenner")]
    assert not any(nf.is_honorific(p) for p in parts)


def test_german_text_gets_only_the_regex_recognisers():
    asked = {}

    class _Analyzer:
        def analyze(self, *, text, language, entities, score_threshold):
            asked["entities"] = set(entities)
            asked["language"] = language
            return []

    detector = PresidioDetector(lambda: _Analyzer())
    detector.detect("Die Wohnung wird für Herrn Winter benötigt.", "de")
    assert "PERSON" not in asked["entities"] and "LOCATION" not in asked["entities"]
    assert asked["entities"] and all(PRESIDIO_KIND[e] in STRUCTURAL_KINDS
                                     for e in asked["entities"])
    assert asked["language"] == "en"            # the regex recognisers are language-agnostic
    detector.detect("The flat is needed for Mr Winter.", "en")
    assert "PERSON" in asked["entities"]


@pytest.mark.parametrize("name,form", [
    ("Lindenhof Hausverwaltung GmbH", "GmbH"),
    ("Halcyon Ventures LLP", "LLP"),
    ("Musterhaus Verwaltungs GmbH & Co. KG", "GmbH & Co. KG"),
    ("Müller und Schmidt GbR", "GbR"),
    ("Meridian Holdings Ltd", "Ltd"),
    ("Lindenhof", None),
])
def test_the_legal_form_is_named_whole(name, form):
    assert legal_form_of(name) == form


def _index(rows, aliases):
    by_token = {r.token: r for r in rows}
    return SimpleNamespace(by_token=by_token, aliases=aliases,
                           token_for=lambda name: next((r.token for r in rows if r.real_value == name), None),
                           canonical=lambda t: t)


def test_the_glossary_carries_the_legal_form_and_no_invented_script():
    org = SimpleNamespace(token="ORG_1", kind="ORG", real_value="Lindenhof Hausverwaltung GmbH",
                          attributes={"jurisdiction": "DE", "roles": ["Landlord"]}, status="active")
    person = SimpleNamespace(token="PERSON_1", kind="PERSON", real_value="Dr. Ada Brenner",
                             attributes={"jurisdiction": "DE", "roles": ["Tenant"],
                                         "entity_type": "individual"},
                             status="active")
    aliases = [SimpleNamespace(token="PERSON_1", source="entity", surface="Dr. Ada Brenner"),
               # generated by the splitter, not observed in any document
               SimpleNamespace(token="PERSON_1", source="fragment",
                               surface=nf.cyrillic_form("Brenner")),
               SimpleNamespace(token="ORG_1", source="entity",
                               surface="Lindenhof Hausverwaltung GmbH")]
    lines = build_glossary(_index([org, person], aliases), {"ORG_1": "x", "PERSON_1": "y"},
                           "ORG_1 kündigt PERSON_1.")
    org_line = next(ln for ln in lines if ln.startswith("ORG_1"))
    person_line = next(ln for ln in lines if ln.startswith("PERSON_1"))
    assert "organisation (GmbH)" in org_line
    assert "Cyrillic" not in person_line


async def test_a_shared_fragment_whose_names_are_all_retired_is_retired_too():
    """A demo scope kept PERSON_5 = "Insert" after every "Insert …" person was retired, so every
    "Insert" in a template would have crossed as a person (23.09.2026)."""
    s = Scope(rows=[
        token_row("PERSON_1", "PERSON", "Insert Title"),
        token_row("PERSON_2", "PERSON", "Insert Rate"),
        token_row("PERSON_5", "PERSON", "Insert",
                  attributes={"fragment": "given", "shared_by": ["PERSON_1", "PERSON_2"]}),
    ])
    report = await s.reconcile()
    by_token = {r.token: r for r in s.rows}
    assert all(by_token[t].status == "retired" for t in ("PERSON_1", "PERSON_2", "PERSON_5"))
    assert by_token["PERSON_5"].canonical_token is None
    assert {"token": "PERSON_5", "value": "Insert",
            "reason": "a part shared only by retired names"} in report["retired"]
    red = await s.tokenize("Insert the date here.", language="en", seed=False)
    assert red.text == "Insert the date here."
